/**
 * Name:       NGUIAGAING SEUGA MARCEL YOURI
 * Instructor:   Sharon Perry
 * Project:     Deliverable 2 Parser
 **/

public enum TokenType {
    // Single-character tokens
    RIGHT_PARANTHESIS, LEFT_PARANTHESIS, IDENTIFIER, NOT_OPERATOR, ASSIGNMENT_OPERATOR, ADDITION_OPERATOR, SUBTRACTION_OPERATOR,
    MULTIPLICATION_OPERATOR, DIVISION_OPERATOR, GREATER_THAN_OPERATOR, LESS_THAN_OPERATOR, NEW_LINE_CHARACTER,

    // Multiple characters tokens
    LESS_THAN_OR_EQUAL_TO_OPERATOR, GREATER_THAN_OR_EQUAL_TO_OPERATOR,
    EQUAL_TO_OPERATOR, NOT_EQUAL_TO_OPERATOR, BLOCK_CHARACTER,

    // Literals
    INTEGER_LITERAL,

    // Keywords
    FUNCTION, PRINT, WHILE, IF, ELSE, END, DO, THEN, FOR, REPEAT, UNTIL,

    // End of file
    EOF
}
